[package]
name = "rmqttraft-warp-memstore"
version = "0.1.0"
authors = ["rmqtt-rs <rmqttd@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.48"
bincode = "1.3"
log = "0.4"
rmqtt-raft = { path = "../..", features = ["reuse"] }
serde = "1.0"
slog-async = "2"
slog-term = "2"
slog = "2"
slog-stdlog = "4"
slog-scope = "4"
structopt = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] , default-features = false}
warp = "0.3"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
once_cell = "1.7.2"
time = "=0.3.20"
scc = { version = "2.0.2",  features = ["serde"] }
